### ISSUE TITLE
Fel data visas i översta grafen

### ISSUE THREAD

**Issue by kloftas** [nordberg/rasp-temp#1]
När du gör limit 72 så tar den bara de 72 första mätvärdena i databasen istället för de 72 senaste. Varför 72 förresten? Det är ju 5-minuters-värden så det blir bara de 6 senaste timmarna som visas. Senaste dygnet vore bättre, dvs limit = 288.

**Comment by kloftas** [comment]
Nu visar den iofs senaste data men grafen är baklänges med färskast data till vänster.

**Comment by nordberg** [comment]
Tror det kan lösas genom att skriva "REVERSE( )" runt queryn. Testar när jag kommer hem.
