### ISSUE TITLE
Automatisk uppdatering

### ISSUE THREAD

**Issue by kloftas** [nordberg/rasp-temp#2]
Vore ju coolt om Raspberryn själv klonade från Github lite då och då så att man inte jobbar på burken alls utan jobbar på en annan dator och sen petar in det i Github varpå det dyker upp live efter nästa automatiska uppdatering.

**Comment by nordberg** [comment]
Ökar inte risken för att man pushar kod som inte fungerar så?

**Comment by kloftas** [comment]
Jo. Då får det väl bli du som ägare som får uppdatera då och då när du känner att det ökar kvaliteten på sidan.
